import Image from 'next/image'
import React from 'react'

const stats = [


    { id: 1, title: "FANBASE", name: 'images generated by Ares Creative', value: '45000' },
    { id: 2, title: "COMMUNITY", name: 'Countries', value: '30+' },
    { id: 3, title: "4 AI MODELS", name:'ARIA CODE', value: '40B' },
    { id: 4, title: "LANGUAGES", name: 'including French & Asian languages', value: '8' },
  ]
  const posts = [
    {
      id: 1,
      title: 'Innovative  training for LLMS & Secured File sharing.',
      description:
        'Faraday models are trained with Rope Scaling for context extension and chain of toughts prompting.',
        image: '/faraday/faraday1.jpg'
    },
    {
      id: 2,
      title: 'Data quality & All-in-One Assistant for  Banking/Chat',
      description:
        'Faraday focus more on data sourcing than quantity of data to train our models. As example, our Aria models are trained on high quality talks from French parliament.',
        image: '/faraday/faraday2.jpg'
    },
    {
      id: 3,
      title: 'Cloud GPU/API',
      description:
        'Faraday model inferences and API are hosted in the cloud. We can deploy models in private clouds trained on the customer data within 20 days.',
        image: '/faraday/faraday3.jpg'
    },
    {
      id: 4,
      title: 'Speed',
      description:
        'Faraday models are faster and less GPU consuming because of the hugging face inference ,AWS Cloud and Nvidia GPUs we are using the scale.',
      image: '/faraday/faraday4.jpg'
       
    },
   
  ]

function page() {
  return (
    <div className='text-center h-full'>
        <img
        src="https://images.unsplash.com/photo-1522071820081-009f0129c71c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2850&q=80&blend=111827&blend-mode=multiply&sat=-100&exp=15"
        alt=""
        className="absolute inset-0 -z-10 h-full w-full object-cover"
      />
        <div className="relative isolate overflow-hidden h-full  py-24 sm:py-32">
        
      
      <div className="relative mx-auto max-w-7xl px-6 lg:px-8">
        
        <div className='flex flex-wrap 2xl:gap-40  justify-center'> 
        <div className="mx-auto max-w-2xl lg:mx-0 lg:max-w-xl">
          <h2 className="text-base font-semibold leading-8 text-indigo-400">OUR SCIENCE LAB PARTNER</h2>
          <h1 >
          FARADAY
          </h1>
          <p className="mt-6 text-lg leading-8 text-gray-300">
            Faraday is building the next generation of artificial intelligence tools for social impact with open source technologies available within an "all-in-one" software called Ares Chat and a secured web browser hosting users data in Europe.
          </p>
        </div>
        
        <Image alt='' src="/faraday/faraday-bg.png" width={300} height={300}/>
        
        </div>
        <dl className="mx-auto mt-16 grid max-w-2xl grid-cols-1 gap-x-8 gap-y-10 text-white sm:mt-20 sm:grid-cols-2 sm:gap-y-16 lg:mx-0 lg:max-w-none lg:grid-cols-4">
          {stats.map((stat) => (
            <div key={stat.id} className="flex flex-col gap-y-3 border-l border-white/10 pl-6">
                <dt className="text-sm leading-6">{stat.title}</dt>
              <dd className=" text-3xl font-semibold tracking-tight">{stat.value}</dd>
              <dt className="text-sm leading-6">{stat.name}</dt>
            </div>
          ))}
        </dl>
      </div>
    </div>
    <div className="mx-auto max-w-7xl px-6 lg:px-8 m-40">
        <div className="mx-auto max-w-2xl text-center">
          <h1 >Features</h1>
          
        </div>
        <div className="mx-auto mt-16 grid max-w-2xl grid-cols-1 gap-x-8 gap-y-20 lg:mx-0 lg:max-w-none lg:grid-cols-4">
          {posts.map((post) => (
            <article key={post.id} className="flex flex-col items-start justify-between">
              <div className="relative w-full">
                <img
                  src={post.image}
                  alt=""
                  className="aspect-[16/9] w-full rounded-2xl bg-gray-100 object-cover sm:aspect-[2/1] lg:aspect-[3/2]"
                />
                <div className="absolute inset-0 rounded-2xl ring-1 ring-inset ring-gray-900/10" />
              </div>
              <div className="max-w-xl">
                
                <div className=" relative">
                  <h3 className="mt-3 text-lg font-semibold leading-6 text-white ">
                  {post.title}
                  </h3>
                  <p className="mt-5 line-clamp-3 text-sm leading-6 text-gray-600">{post.description}</p>
                </div>
                
              </div>
            </article>
          ))}
        </div>
      </div>
    </div>
  )
}

export default page